### ISSUE TITLE
Integración con terceros

### ISSUE THREAD

**Issue by koldLight** [PyLadiesMadrid/pycartociudad#8]
Ahora la estructura base tiene lo necesario para:

* generar la doc con sphinx y publicarla en readthedocs
* tener la integración continua (correr tests, etc) con travisCI

Hace falta tener ciertos permisos a nivel de organización (pyladiesmadrid) para linkar el repo con readthedocs + travisci. Los links que deberían funcionar una vez linkadas las apps son:

* https://pycartociudad.readthedocs.io/en/latest/?badge=latest
* https://travis-ci.com/pyladiesmadrid/pycartociudad

Si te puedes encargar tú de linkar las dos, @aliciapj estaría genial :)

**Comment by aliciapj** [comment]
La integración con readthedocs ya está. 
Con travis supuestamente también... pero como aun no tenemos tests no sale nada. Cuando probemos con un test lo verifico bien y cierro el issue :slightly_smiling_face:

**Comment by koldLight** [comment]
genial, muchas gracias!

**Comment by koldLight** [comment]
Cierro que funcionan las dos integraciones bien!
